#!/bin/bash

set -x

rename_and_reweight_font () {
    font_name=$1
    maybe_font_style=$2
    custom_wght=$3
    source_file=UbuntuSans${maybe_font_style}'[wdth,wght].ttf'
    target_file=${font_name}Sans${maybe_font_style}'[wdth,wght]'
    target_file_ttf=$target_file.ttf
    target_file_ttx=$target_file.ttx

    if [ -n "$custom_wght" ]; then
        cp $source_file $target_file_ttf.tmp &&
        fonttools varLib.instancer -o $target_file_ttf $target_file_ttf.tmp wght=$custom_wght &&
        rm $target_file_ttf.tmp
    else
        cp $source_file $target_file_ttf
    fi &&
    ttx $target_file_ttf &&
    rm $target_file_ttf &&
    perl -0777 -pi -e "s/Ubuntu/${font_name}/g" $target_file_ttx &&
    ttx $target_file_ttx &&
    rm $target_file_ttx &&
    mv $target_file_ttf ../../fonts2/
}

create_mutant () {
    font_name=$1
    custom_wght=$2
    skip_italic=${3:-false}
    cd fonts/variable &&
    rename_and_reweight_font "$font_name" "" "$custom_wght" &&
    if [ "$skip_italic" = false ]; then
        rename_and_reweight_font "$font_name" "-Italic" "$custom_wght"
    fi &&
    cd -
}

rm -rf fonts2 2>/dev/null
pyenv local 3.8.20 &&
mkdir fonts2 &&
echo "Creating Ubuntu Sans variable fonts..." &&
make dev &&
echo "Creating Bubuntu Sans (only a rename) variable fonts... (for LibreOffice Writer 7.3.7.2 with GDI font rendering)" &&
create_mutant Bubuntu &&
echo "Creating Cubuntu Sans variable fonts... (with weight 473, for MacType global [FontSubstitutes] section)" &&
create_mutant Cubuntu "100:473:800" &&
echo "Creating Dubuntu Sans variable fonts... (for Chromium Browsers)" &&
create_mutant Dubuntu "500:800" &&
echo "Creating Fubuntu Sans variable font... (for Android)" &&
create_mutant Fubuntu "100:550:800" true &&
git checkout ./fonts/
rm fonts/variable/*Beta*.ttf 2>/dev/null
rm .python-version
